### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by GatsbyChen** [AnanthK1998/Nuclei-segmentation-MICCAI-2018-Challenge-#1]
Could you send me the Dataset of "Segmentation of Nuclei in Images" ? My email site is 18842647783@163.com, thank you very much!

**Comment by AnanthK1998** [comment]
Hi @GatsbyChen , you can access the dataset at https://monuseg.grand-challenge.org/Data/

**Comment by GatsbyChen** [comment]
Yeah！I got it. Thank you!
